### ISSUE TITLE
Either expose KICS version or keep docker image minor version up to date

### ISSUE THREAD

**Issue by erzz** [Checkmarx/kics-github-action#101]
You guys do a great job with the KICS project releasing lots of new stuff - but we cannot benefit from it when we are stuck with the hardcoded 1.7 docker image in the action.

Currently that image contains 1.7.8 when the project is currently at 1.7.11

![image](https://github.com/Checkmarx/kics-github-action/assets/58994586/6394a153-068c-4cbf-9d52-96b76c5de95a)

So can I suggest that you either expose the docker image version as an input or automate the builds of the minor version image to follow latest patch version? 🙏🏻

**Comment by gabriel-cx** [comment]
Hi @erzz ,

Thank you for your inputs.
We always keep the kics version inside the github action at least 1 step behind the latest. We will update the version on the github action to v1.7.10 asap.

**Comment by gabriel-cx** [comment]
@erzz kindly be aware that kics github action is now using kics v1.7.10.
Feel free to re-open the issue or open a new one if you need our support.
