### ISSUE TITLE
Any option to specify multiple query paths?

### ISSUE THREAD

**Issue by koushik-goswami** [Checkmarx/kics-github-action#41]
By default the scan points to the default query path ./assets/queris. If I specify a separate path to my custom queries, all the default queries get overridden. Is there a feature in the plan to specify multiple query paths?

**Comment by rafaela-soares** [comment]
Hi, @koushik-goswami 🙂 Thank you so much for reaching us!

We are happy to inform you that we are working on that in PR https://github.com/Checkmarx/kics/pull/4813!

**Comment by koushik-goswami** [comment]
Awesome! Thanks.

**Comment by kaplanlior** [comment]
The fix is part of KICS 1.5.2, and would be soon also available in the github action.

**Comment by rafaela-soares** [comment]
Hello, @koushik-goswami 🙂 

The KICS GitHub Action is updated to version 1.5.2, along with your suggestion! Thank you so much!
