### ISSUE TITLE
Can you update to latest kics version?

### ISSUE THREAD

**Issue by raserma** [Checkmarx/kics-github-action#48]
KICS upstream repo is already running [1.5.5](https://github.com/Checkmarx/kics/releases/tag/v1.5.5) and would be great to get such updates on this GHA.

Thanks!

**Comment by jycamier** [comment]
Hi @rafaela-soares 
Any possibility to have the update to `v1.5.10` ? 

Cannot wait the fix of terraform aws v4 provider 😝

**Comment by nunoocx** [comment]
Hi @jycamier GHA was updated to v1.5.10!

There's this know issue related with dockerfiles ([KICS-5465](https://github.com/Checkmarx/kics/issues/5465)), though. 
We already have a fix for it, shipping it in the next release.

**Comment by jycamier** [comment]
Hi @nunoocx 
Thank you for you anwser.

What about a bump of the action itself to get the last features ?

**Comment by gabriel-cx** [comment]
Hi @raserma  and @jycamier

Thanks for your feedback!

Currently, if you use **KICS GH Action v1.6** means that you will scan your IaC files with **KICS version 1.6.1**.
If you use **KICS GH Action v1.5 or below** you will be scanning your files with  **KICS version 1.5.15**.

Is this information what you looking for?
if so, kindly close this issue. if not, feel free to leave a message or contact me directly. ⛵
